/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type DateRange = {
    startDate?: string;
    endDate?: string;
};

export type SanityImageAssetReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type BackgroundImage = {
    _type: 'backgroundImage';
    image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
    opacity?: number;
};

export type CustomImage = {
    _type: 'customImage';
    image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
    alt?: string;
    sizingMode?: 'cover' | 'container' | 'fill' | 'stretch';
    backgroundColor?: string;
};

export type Card = {
    _type: 'card';
    badge?: Badge;
    heading?: string;
    body?: Markdown;
    cta?: Array<
        | ({
              _key: string;
          } & ActionButton)
        | ({
              _key: string;
          } & ActionLink)
    >;
    image?: CustomImage;
    theme?: 'light' | 'dark' | 'transparent';
    textAlign?: 'left' | 'center';
    hasBorder?: boolean;
};

export type Badge = {
    _type: 'badge';
    label?: string;
    theme?: 'primary' | 'secondary' | 'accent' | 'neutral';
};

export type ActionLink = {
    _type: 'actionLink';
    label: string;
    url?: string;
    ariaLabel?: string;
    target?: '_self' | '_blank';
};

export type ActionButton = {
    _type: 'actionButton';
    label: string;
    url?: string;
    ariaLabel?: string;
    target?: '_self' | '_blank';
    theme?: 'primary' | 'secondary' | 'accent' | 'neutral';
};

export type SamplingSiteReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'samplingSite';
};

export type WaterQualitySection = {
    _type: 'waterQualitySection';
    heading?: string;
    body?: Markdown;
    showChart?: boolean;
    showTable?: boolean;
    siteFilter?: Array<
        {
            _key: string;
        } & SamplingSiteReference
    >;
    dateRange?: DateRange;
    chartType?: 'line' | 'bar';
    showThresholds?: boolean;
    cta?: Array<
        | ({
              _key: string;
          } & ActionButton)
        | ({
              _key: string;
          } & ActionLink)
    >;
    theme?: 'light' | 'dark';
    backgroundImage?: BackgroundImage;
    width?: 'full' | 'inset';
};

export type TestimonialsSection = {
    _type: 'testimonialsSection';
    heading?: string;
    body?: Markdown;
    items?: Array<
        {
            _key: string;
        } & Testimonial
    >;
    theme?: 'light' | 'dark';
    backgroundImage?: BackgroundImage;
    width?: 'full' | 'inset';
    columns?: 'one' | 'two';
};

export type LogosSection = {
    _type: 'logosSection';
    heading?: string;
    body?: Markdown;
    items?: Array<
        {
            _key: string;
        } & CustomImage
    >;
    theme?: 'light' | 'dark';
    backgroundImage?: BackgroundImage;
    width?: 'full' | 'inset';
    motion?: 'static' | 'moveToLeft' | 'moveToRight';
};

export type CtaSection = {
    _type: 'ctaSection';
    heading?: string;
    body?: Markdown;
    cta?: Array<
        | ({
              _key: string;
          } & ActionButton)
        | ({
              _key: string;
          } & ActionLink)
    >;
    theme?: 'light' | 'dark';
    backgroundImage?: BackgroundImage;
    width?: 'full' | 'inset';
};

export type CardsSection = {
    _type: 'cardsSection';
    heading?: string;
    body?: Markdown;
    items?: Array<
        {
            _key: string;
        } & Card
    >;
    theme?: 'light' | 'dark';
    backgroundImage?: BackgroundImage;
    width?: 'full' | 'inset';
    columns?: 'one' | 'two' | 'three' | 'four';
    fixedImageHeight?: boolean;
};

export type HeroSection = {
    _type: 'heroSection';
    heading?: string;
    body?: Markdown;
    cta?: Array<
        | ({
              _key: string;
          } & ActionButton)
        | ({
              _key: string;
          } & ActionLink)
    >;
    height?: 'small' | 'medium' | 'large' | 'full';
    backgroundImageFit?: 'cover' | 'contain' | 'fill';
    theme?: 'light' | 'dark';
    backgroundImage?: BackgroundImage;
    width?: 'full' | 'inset';
};

export type ContactMessage = {
    _id: string;
    _type: 'contactMessage';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string;
    email: string;
    topic?: 'General enquiry' | 'Volunteering' | 'Media/press';
    message: string;
    consent?: boolean;
    ipHash?: string;
    userAgent?: string;
    spamStatus?: 'clean' | 'suspicious';
    spamReasons?: Array<string>;
    turnstileOutcome?: 'success';
    reviewedAt?: string;
    createdAt?: string;
};

export type WaterSample = {
    _id: string;
    _type: 'waterSample';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    date: string;
    site: SamplingSiteReference;
    ecoli?: number;
    enterococci?: number;
    rainfall?: number;
    notes?: string;
    labReference?: string;
};

export type SamplingSite = {
    _id: string;
    _type: 'samplingSite';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    description?: string;
    coordinates?: {
        lat?: number;
        lng?: number;
    };
    notes?: string;
};

export type Slug = {
    _type: 'slug';
    current: string;
    source?: string;
};

export type Footer = {
    _type: 'footer';
    text?: string;
};

export type Header = {
    _type: 'header';
    title: string;
    logo?: CustomImage;
    navLinks?: Array<
        | ({
              _key: string;
          } & ActionButton)
        | ({
              _key: string;
          } & ActionLink)
    >;
};

export type SiteConfig = {
    _id: string;
    _type: 'siteConfig';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    favicon?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
    header?: Header;
    footer?: Footer;
    titleSuffix?: string;
    monitoringConfiguration?: {
        primaryLocation?: {
            name?: string;
            center?: {
                lat: number;
                lng: number;
            };
            defaultRadius: number;
            description?: string;
        };
        riverStations?: {
            freshwaterStationId?: string;
            tidalStationId?: string;
        };
        bathingWaters?: Array<{
            id: string;
            label: string;
            _key: string;
        }>;
    };
};

export type SanityImageCrop = {
    _type: 'sanity.imageCrop';
    top: number;
    bottom: number;
    left: number;
    right: number;
};

export type SanityImageHotspot = {
    _type: 'sanity.imageHotspot';
    x: number;
    y: number;
    height: number;
    width: number;
};

export type PersonReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'person';
};

export type Testimonial = {
    _type: 'testimonial';
    quote?: Markdown;
    author?: PersonReference;
    theme?: 'light' | 'dark' | 'transparent';
    hasBorder?: boolean;
};

export type Post = {
    _id: string;
    _type: 'post';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    excerpt?: string;
    author: PersonReference;
    publishedAt: string;
    featuredImage?: CustomImage;
    body: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    seoTitle?: string;
    seoDescription?: string;
    seoKeywords?: string;
};

export type CompanyReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'company';
};

export type Person = {
    _id: string;
    _type: 'person';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string;
    title?: string;
    image?: CustomImage;
    company?: CompanyReference;
};

export type Company = {
    _id: string;
    _type: 'company';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string;
    logo?: CustomImage;
};

export type Page = {
    _id: string;
    _type: 'page';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    sections?: Array<
        | ({
              _key: string;
          } & CardsSection)
        | ({
              _key: string;
          } & CtaSection)
        | ({
              _key: string;
          } & HeroSection)
        | ({
              _key: string;
          } & LogosSection)
        | ({
              _key: string;
          } & TestimonialsSection)
        | ({
              _key: string;
          } & WaterQualitySection)
    >;
    metaTitle?: string;
    addTitleSuffix?: boolean;
    metaDescription?: string;
    socialImage?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
};

export type Markdown = string;

export type MediaTag = {
    _id: string;
    _type: 'media.tag';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: Slug;
};

export type SanityImagePaletteSwatch = {
    _type: 'sanity.imagePaletteSwatch';
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: 'sanity.imagePalette';
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: 'sanity.imageDimensions';
    height: number;
    width: number;
    aspectRatio: number;
};

export type SanityImageMetadata = {
    _type: 'sanity.imageMetadata';
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    thumbHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type SanityFileAsset = {
    _id: string;
    _type: 'sanity.fileAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: 'sanity.assetSourceData';
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageAsset = {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type Geopoint = {
    _type: 'geopoint';
    lat?: number;
    lng?: number;
    alt?: number;
};

export type AllSanitySchemaTypes =
    | DateRange
    | SanityImageAssetReference
    | BackgroundImage
    | CustomImage
    | Card
    | Badge
    | ActionLink
    | ActionButton
    | SamplingSiteReference
    | WaterQualitySection
    | TestimonialsSection
    | LogosSection
    | CtaSection
    | CardsSection
    | HeroSection
    | ContactMessage
    | WaterSample
    | SamplingSite
    | Slug
    | Footer
    | Header
    | SiteConfig
    | SanityImageCrop
    | SanityImageHotspot
    | PersonReference
    | Testimonial
    | Post
    | CompanyReference
    | Person
    | Company
    | Page
    | Markdown
    | MediaTag
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageMetadata
    | SanityFileAsset
    | SanityAssetSourceData
    | SanityImageAsset
    | Geopoint;

// Source: ../src/data/blocks.ts
// Variable: IMAGE
// Query: {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }
export type IMAGE_RESULT = {
    _id: never;
    asset: never;
    dimensions: never;
    alt: never;
    hotspot: never;
    crop: never;
};

// Source: ../src/data/blocks.ts
// Variable: SECTIONS
// Query: {  ...,  backgroundImage {    ...,    "image": {      "_id": image.asset->_id,      "asset": image.asset,      "dimensions": image.asset->metadata.dimensions,      "hotspot": image.hotspot,      "crop": image.crop    }  },  _type == "cardsSection" => {    ...,    items[] {      ...,      image   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }    }  },  _type == "logosSection" => {    items[]   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }  },  _type == "testimonialsSection" => {    items[] {        ...,        author-> {            _type,            _id,            name,            title,            image   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  },            company-> {                _type,                _id,                name,                logo   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }            }        }    }  },}
export type SECTIONS_RESULT = never;

// Source: ../src/data/page.ts
// Variable: PAGE_PROJECTION
// Query: {  _id,  slug,  title,  metaTitle,  metaDescription,  "socialImage": {    "src": socialImage.asset->url  },  sections[] {  ...,  backgroundImage {    ...,    "image": {      "_id": image.asset->_id,      "asset": image.asset,      "dimensions": image.asset->metadata.dimensions,      "hotspot": image.hotspot,      "crop": image.crop    }  },  _type == "cardsSection" => {    ...,    items[] {      ...,      image   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }    }  },  _type == "logosSection" => {    items[]   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }  },  _type == "testimonialsSection" => {    items[] {        ...,        author-> {            _type,            _id,            name,            title,            image   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  },            company-> {                _type,                _id,                name,                logo   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }            }        }    }  },}}
export type PAGE_PROJECTION_RESULT = {
    _id: never;
    slug: never;
    title: never;
    metaTitle: never;
    metaDescription: never;
    socialImage: {
        src: never;
    };
    sections: never;
};

// Source: ../src/data/page.ts
// Variable: PAGES_QUERY
// Query: *[_type == "page"] {  _id,  slug,  title,  metaTitle,  metaDescription,  "socialImage": {    "src": socialImage.asset->url  },  sections[] {  ...,  backgroundImage {    ...,    "image": {      "_id": image.asset->_id,      "asset": image.asset,      "dimensions": image.asset->metadata.dimensions,      "hotspot": image.hotspot,      "crop": image.crop    }  },  _type == "cardsSection" => {    ...,    items[] {      ...,      image   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }    }  },  _type == "logosSection" => {    items[]   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }  },  _type == "testimonialsSection" => {    items[] {        ...,        author-> {            _type,            _id,            name,            title,            image   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  },            company-> {                _type,                _id,                name,                logo   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }            }        }    }  },}}
export type PAGES_QUERY_RESULT = Array<{
    _id: string;
    slug: Slug;
    title: string;
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
        src: string | null;
    };
    sections: Array<
        | {
              _key: string;
              _type: 'cardsSection';
              heading?: string;
              body?: Markdown;
              items: Array<{
                  _key: string;
                  _type: 'card';
                  badge?: Badge;
                  heading?: string;
                  body?: Markdown;
                  cta?: Array<
                      | ({
                            _key: string;
                        } & ActionButton)
                      | ({
                            _key: string;
                        } & ActionLink)
                  >;
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      alt: string | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  } | null;
                  theme?: 'dark' | 'light' | 'transparent';
                  textAlign?: 'center' | 'left';
                  hasBorder?: boolean;
              }> | null;
              theme?: 'dark' | 'light';
              backgroundImage?: BackgroundImage;
              width?: 'full' | 'inset';
              columns?: 'four' | 'one' | 'three' | 'two';
              fixedImageHeight?: boolean;
          }
        | {
              _key: string;
              _type: 'ctaSection';
              heading?: string;
              body?: Markdown;
              cta?: Array<
                  | ({
                        _key: string;
                    } & ActionButton)
                  | ({
                        _key: string;
                    } & ActionLink)
              >;
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
          }
        | {
              _key: string;
              _type: 'heroSection';
              heading?: string;
              body?: Markdown;
              cta?: Array<
                  | ({
                        _key: string;
                    } & ActionButton)
                  | ({
                        _key: string;
                    } & ActionLink)
              >;
              height?: 'full' | 'large' | 'medium' | 'small';
              backgroundImageFit?: 'contain' | 'cover' | 'fill';
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
          }
        | {
              _key: string;
              _type: 'logosSection';
              heading?: string;
              body?: Markdown;
              items: Array<{
                  _id: string | null;
                  asset: SanityImageAssetReference | null;
                  dimensions: SanityImageDimensions | null;
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
              }> | null;
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
              motion?: 'moveToLeft' | 'moveToRight' | 'static';
          }
        | {
              _key: string;
              _type: 'testimonialsSection';
              heading?: string;
              body?: Markdown;
              items: Array<{
                  _key: string;
                  _type: 'testimonial';
                  quote?: Markdown;
                  author: {
                      _type: 'person';
                      _id: string;
                      name: string;
                      title: string | null;
                      image: {
                          _id: string | null;
                          asset: SanityImageAssetReference | null;
                          dimensions: SanityImageDimensions | null;
                          alt: string | null;
                          hotspot: SanityImageHotspot | null;
                          crop: SanityImageCrop | null;
                      } | null;
                      company: {
                          _type: 'company';
                          _id: string;
                          name: string;
                          logo: {
                              _id: string | null;
                              asset: SanityImageAssetReference | null;
                              dimensions: SanityImageDimensions | null;
                              alt: string | null;
                              hotspot: SanityImageHotspot | null;
                              crop: SanityImageCrop | null;
                          } | null;
                      } | null;
                  } | null;
                  theme?: 'dark' | 'light' | 'transparent';
                  hasBorder?: boolean;
              }> | null;
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
              columns?: 'one' | 'two';
          }
        | {
              _key: string;
              _type: 'waterQualitySection';
              heading?: string;
              body?: Markdown;
              showChart?: boolean;
              showTable?: boolean;
              siteFilter?: Array<
                  {
                      _key: string;
                  } & SamplingSiteReference
              >;
              dateRange?: DateRange;
              chartType?: 'bar' | 'line';
              showThresholds?: boolean;
              cta?: Array<
                  | ({
                        _key: string;
                    } & ActionButton)
                  | ({
                        _key: string;
                    } & ActionLink)
              >;
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
          }
    > | null;
}>;

// Source: ../src/data/page.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug] {  _id,  slug,  title,  metaTitle,  metaDescription,  "socialImage": {    "src": socialImage.asset->url  },  sections[] {  ...,  backgroundImage {    ...,    "image": {      "_id": image.asset->_id,      "asset": image.asset,      "dimensions": image.asset->metadata.dimensions,      "hotspot": image.hotspot,      "crop": image.crop    }  },  _type == "cardsSection" => {    ...,    items[] {      ...,      image   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }    }  },  _type == "logosSection" => {    items[]   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }  },  _type == "testimonialsSection" => {    items[] {        ...,        author-> {            _type,            _id,            name,            title,            image   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  },            company-> {                _type,                _id,                name,                logo   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }            }        }    }  },}}
export type PAGE_BY_SLUG_QUERY_RESULT = Array<{
    _id: string;
    slug: Slug;
    title: string;
    metaTitle: string | null;
    metaDescription: string | null;
    socialImage: {
        src: string | null;
    };
    sections: Array<
        | {
              _key: string;
              _type: 'cardsSection';
              heading?: string;
              body?: Markdown;
              items: Array<{
                  _key: string;
                  _type: 'card';
                  badge?: Badge;
                  heading?: string;
                  body?: Markdown;
                  cta?: Array<
                      | ({
                            _key: string;
                        } & ActionButton)
                      | ({
                            _key: string;
                        } & ActionLink)
                  >;
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      alt: string | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  } | null;
                  theme?: 'dark' | 'light' | 'transparent';
                  textAlign?: 'center' | 'left';
                  hasBorder?: boolean;
              }> | null;
              theme?: 'dark' | 'light';
              backgroundImage?: BackgroundImage;
              width?: 'full' | 'inset';
              columns?: 'four' | 'one' | 'three' | 'two';
              fixedImageHeight?: boolean;
          }
        | {
              _key: string;
              _type: 'ctaSection';
              heading?: string;
              body?: Markdown;
              cta?: Array<
                  | ({
                        _key: string;
                    } & ActionButton)
                  | ({
                        _key: string;
                    } & ActionLink)
              >;
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
          }
        | {
              _key: string;
              _type: 'heroSection';
              heading?: string;
              body?: Markdown;
              cta?: Array<
                  | ({
                        _key: string;
                    } & ActionButton)
                  | ({
                        _key: string;
                    } & ActionLink)
              >;
              height?: 'full' | 'large' | 'medium' | 'small';
              backgroundImageFit?: 'contain' | 'cover' | 'fill';
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
          }
        | {
              _key: string;
              _type: 'logosSection';
              heading?: string;
              body?: Markdown;
              items: Array<{
                  _id: string | null;
                  asset: SanityImageAssetReference | null;
                  dimensions: SanityImageDimensions | null;
                  alt: string | null;
                  hotspot: SanityImageHotspot | null;
                  crop: SanityImageCrop | null;
              }> | null;
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
              motion?: 'moveToLeft' | 'moveToRight' | 'static';
          }
        | {
              _key: string;
              _type: 'testimonialsSection';
              heading?: string;
              body?: Markdown;
              items: Array<{
                  _key: string;
                  _type: 'testimonial';
                  quote?: Markdown;
                  author: {
                      _type: 'person';
                      _id: string;
                      name: string;
                      title: string | null;
                      image: {
                          _id: string | null;
                          asset: SanityImageAssetReference | null;
                          dimensions: SanityImageDimensions | null;
                          alt: string | null;
                          hotspot: SanityImageHotspot | null;
                          crop: SanityImageCrop | null;
                      } | null;
                      company: {
                          _type: 'company';
                          _id: string;
                          name: string;
                          logo: {
                              _id: string | null;
                              asset: SanityImageAssetReference | null;
                              dimensions: SanityImageDimensions | null;
                              alt: string | null;
                              hotspot: SanityImageHotspot | null;
                              crop: SanityImageCrop | null;
                          } | null;
                      } | null;
                  } | null;
                  theme?: 'dark' | 'light' | 'transparent';
                  hasBorder?: boolean;
              }> | null;
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
              columns?: 'one' | 'two';
          }
        | {
              _key: string;
              _type: 'waterQualitySection';
              heading?: string;
              body?: Markdown;
              showChart?: boolean;
              showTable?: boolean;
              siteFilter?: Array<
                  {
                      _key: string;
                  } & SamplingSiteReference
              >;
              dateRange?: DateRange;
              chartType?: 'bar' | 'line';
              showThresholds?: boolean;
              cta?: Array<
                  | ({
                        _key: string;
                    } & ActionButton)
                  | ({
                        _key: string;
                    } & ActionLink)
              >;
              theme?: 'dark' | 'light';
              backgroundImage: {
                  _type: 'backgroundImage';
                  image: {
                      _id: string | null;
                      asset: SanityImageAssetReference | null;
                      dimensions: SanityImageDimensions | null;
                      hotspot: SanityImageHotspot | null;
                      crop: SanityImageCrop | null;
                  };
                  opacity?: number;
              } | null;
              width?: 'full' | 'inset';
          }
    > | null;
}>;

// Source: ../src/data/siteConfig.ts
// Variable: CONFIG_QUERY_OBJ
// Query: {  _id,  "favicon": {    "src": favicon.asset->url  },  header {    ...,    logo   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }  },  footer,  titleSuffix,  monitoringConfiguration {    primaryLocation {      name,      center {        lat,        lng      },      defaultRadius,      description    },    riverStations {      freshwaterStationId,      tidalStationId    },    bathingWaters[] {      id,      label    }  }}
export type CONFIG_QUERY_OBJ_RESULT = {
    _id: never;
    favicon: {
        src: never;
    };
    header: never;
    footer: never;
    titleSuffix: never;
    monitoringConfiguration: never;
};

// Source: ../src/data/siteConfig.ts
// Variable: SITE_CONFIG_QUERY
// Query: *[_type == "siteConfig"][0] {  _id,  "favicon": {    "src": favicon.asset->url  },  header {    ...,    logo   {    "_id": image.asset->_id,    "asset": image.asset,    "dimensions": image.asset->metadata.dimensions,    "alt": alt,    "hotspot": image.hotspot,    "crop": image.crop  }  },  footer,  titleSuffix,  monitoringConfiguration {    primaryLocation {      name,      center {        lat,        lng      },      defaultRadius,      description    },    riverStations {      freshwaterStationId,      tidalStationId    },    bathingWaters[] {      id,      label    }  }}
export type SITE_CONFIG_QUERY_RESULT = {
    _id: string;
    favicon: {
        src: string | null;
    };
    header: {
        _type: 'header';
        title: string;
        logo: {
            _id: string | null;
            asset: SanityImageAssetReference | null;
            dimensions: SanityImageDimensions | null;
            alt: string | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
        } | null;
        navLinks?: Array<
            | ({
                  _key: string;
              } & ActionButton)
            | ({
                  _key: string;
              } & ActionLink)
        >;
    } | null;
    footer: Footer | null;
    titleSuffix: string | null;
    monitoringConfiguration: {
        primaryLocation: {
            name: string | null;
            center: {
                lat: number;
                lng: number;
            } | null;
            defaultRadius: number;
            description: string | null;
        } | null;
        riverStations: {
            freshwaterStationId: string | null;
            tidalStationId: string | null;
        } | null;
        bathingWaters: Array<{
            id: string;
            label: string;
        }> | null;
    } | null;
} | null;

// Source: ../src/data/waterQuality.ts
// Variable: SAMPLES_QUERY
// Query: *[_type == "waterSample"] | order(date desc) {    _id,    date,    "siteName": site->title,    "siteSlug": site->slug.current,    ecoli,    enterococci,    rainfall,    notes  }
export type SAMPLES_QUERY_RESULT = Array<{
    _id: string;
    date: string;
    siteName: string;
    siteSlug: string;
    ecoli: number | null;
    enterococci: number | null;
    rainfall: number | null;
    notes: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
    interface SanityQueries {
        '\n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n': IMAGE_RESULT;
        '{\n  ...,\n  backgroundImage {\n    ...,\n    "image": {\n      "_id": image.asset->_id,\n      "asset": image.asset,\n      "dimensions": image.asset->metadata.dimensions,\n      "hotspot": image.hotspot,\n      "crop": image.crop\n    }\n  },\n  _type == "cardsSection" => {\n    ...,\n    items[] {\n      ...,\n      image \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n    }\n  },\n  _type == "logosSection" => {\n    items[] \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n  },\n  _type == "testimonialsSection" => {\n    items[] {\n        ...,\n        author-> {\n            _type,\n            _id,\n            name,\n            title,\n            image \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n,\n            company-> {\n                _type,\n                _id,\n                name,\n                logo \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n            }\n        }\n    }\n  },\n}': SECTIONS_RESULT;
        '{\n  _id,\n  slug,\n  title,\n  metaTitle,\n  metaDescription,\n  "socialImage": {\n    "src": socialImage.asset->url\n  },\n  sections[] {\n  ...,\n  backgroundImage {\n    ...,\n    "image": {\n      "_id": image.asset->_id,\n      "asset": image.asset,\n      "dimensions": image.asset->metadata.dimensions,\n      "hotspot": image.hotspot,\n      "crop": image.crop\n    }\n  },\n  _type == "cardsSection" => {\n    ...,\n    items[] {\n      ...,\n      image \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n    }\n  },\n  _type == "logosSection" => {\n    items[] \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n  },\n  _type == "testimonialsSection" => {\n    items[] {\n        ...,\n        author-> {\n            _type,\n            _id,\n            name,\n            title,\n            image \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n,\n            company-> {\n                _type,\n                _id,\n                name,\n                logo \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n            }\n        }\n    }\n  },\n}\n}': PAGE_PROJECTION_RESULT;
        '*[_type == "page"] {\n  _id,\n  slug,\n  title,\n  metaTitle,\n  metaDescription,\n  "socialImage": {\n    "src": socialImage.asset->url\n  },\n  sections[] {\n  ...,\n  backgroundImage {\n    ...,\n    "image": {\n      "_id": image.asset->_id,\n      "asset": image.asset,\n      "dimensions": image.asset->metadata.dimensions,\n      "hotspot": image.hotspot,\n      "crop": image.crop\n    }\n  },\n  _type == "cardsSection" => {\n    ...,\n    items[] {\n      ...,\n      image \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n    }\n  },\n  _type == "logosSection" => {\n    items[] \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n  },\n  _type == "testimonialsSection" => {\n    items[] {\n        ...,\n        author-> {\n            _type,\n            _id,\n            name,\n            title,\n            image \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n,\n            company-> {\n                _type,\n                _id,\n                name,\n                logo \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n            }\n        }\n    }\n  },\n}\n}': PAGES_QUERY_RESULT;
        '*[_type == "page" && slug.current == $slug] {\n  _id,\n  slug,\n  title,\n  metaTitle,\n  metaDescription,\n  "socialImage": {\n    "src": socialImage.asset->url\n  },\n  sections[] {\n  ...,\n  backgroundImage {\n    ...,\n    "image": {\n      "_id": image.asset->_id,\n      "asset": image.asset,\n      "dimensions": image.asset->metadata.dimensions,\n      "hotspot": image.hotspot,\n      "crop": image.crop\n    }\n  },\n  _type == "cardsSection" => {\n    ...,\n    items[] {\n      ...,\n      image \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n    }\n  },\n  _type == "logosSection" => {\n    items[] \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n  },\n  _type == "testimonialsSection" => {\n    items[] {\n        ...,\n        author-> {\n            _type,\n            _id,\n            name,\n            title,\n            image \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n,\n            company-> {\n                _type,\n                _id,\n                name,\n                logo \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n            }\n        }\n    }\n  },\n}\n}': PAGE_BY_SLUG_QUERY_RESULT;
        '{\n  _id,\n  "favicon": {\n    "src": favicon.asset->url\n  },\n  header {\n    ...,\n    logo \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n  },\n  footer,\n  titleSuffix,\n  monitoringConfiguration {\n    primaryLocation {\n      name,\n      center {\n        lat,\n        lng\n      },\n      defaultRadius,\n      description\n    },\n    riverStations {\n      freshwaterStationId,\n      tidalStationId\n    },\n    bathingWaters[] {\n      id,\n      label\n    }\n  }\n}': CONFIG_QUERY_OBJ_RESULT;
        '*[_type == "siteConfig"][0] {\n  _id,\n  "favicon": {\n    "src": favicon.asset->url\n  },\n  header {\n    ...,\n    logo \n  {\n    "_id": image.asset->_id,\n    "asset": image.asset,\n    "dimensions": image.asset->metadata.dimensions,\n    "alt": alt,\n    "hotspot": image.hotspot,\n    "crop": image.crop\n  }\n\n  },\n  footer,\n  titleSuffix,\n  monitoringConfiguration {\n    primaryLocation {\n      name,\n      center {\n        lat,\n        lng\n      },\n      defaultRadius,\n      description\n    },\n    riverStations {\n      freshwaterStationId,\n      tidalStationId\n    },\n    bathingWaters[] {\n      id,\n      label\n    }\n  }\n}': SITE_CONFIG_QUERY_RESULT;
        '\n  *[_type == "waterSample"] | order(date desc) {\n    _id,\n    date,\n    "siteName": site->title,\n    "siteSlug": site->slug.current,\n    ecoli,\n    enterococci,\n    rainfall,\n    notes\n  }\n': SAMPLES_QUERY_RESULT;
    }
}
